"""add giveaway description

Revision ID: 0315bb026335
Revises: 6498e59c776a
Create Date: 2024-06-22 16:21:23.965274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0315bb026335'
down_revision = '6498e59c776a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giveaway', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giveaway', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
