"""create photos table

Revision ID: 667cd047c345
Revises: d2ff150a2d83
Create Date: 2024-05-22 14:21:40.685756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667cd047c345'
down_revision = 'd2ff150a2d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
