"""empty message

Revision ID: cd13b5e0dc4f
Revises: 6eda4901a79e
Create Date: 2024-03-27 12:27:26.984475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd13b5e0dc4f'
down_revision = '6eda4901a79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winner')
    # ### end Alembic commands ###
