"""add photos

Revision ID: d4453a8492e1
Revises: f56a74e20f89
Create Date: 2024-06-01 14:25:54.437764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4453a8492e1'
down_revision = 'f56a74e20f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloudflare_id', sa.Integer(), nullable=True),
    sa.Column('giveaway_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
