"""rollback add photo

Revision ID: f56a74e20f89
Revises: 7497bd4778e9
Create Date: 2024-05-28 12:19:16.746287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f56a74e20f89'
down_revision = '7497bd4778e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('giveaway_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], name='photo_giveaway_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photo_pkey')
    )
    # ### end Alembic commands ###
